import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    // 'intro',
    {
      type: 'category',
      label: 'FUEL',
      // link:{
      //   type: 'doc',
      //   id:'FUEL/fuel'
      // },
      items:[
        {
          type:'category',
          label:'Wallet APIs',
          link:{
            type: 'doc',
            id:'FUEL/wallet-apis/fuel-wallet'
          },
          items:[
              
            'FUEL/wallet-apis/prerequisites/prerequisites',
            {
              type:'category',
              label:'Integration',
              link:{
                type: 'doc',
                id:'FUEL/wallet-apis/integration/integration'
              },
              items:[
                'FUEL/wallet-apis/integration/feat/fuel-overview',
                'FUEL/wallet-apis/integration/feat/fuel-create-wallet',
                'FUEL/wallet-apis/integration/feat/fuel-get-created-wallet',

              ]
            }
            
          ],
          
        }
      ]
      
    },
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  ],
  
};

export default sidebars;
