import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [

    {
      type: 'doc',
      id: 'lync-introduction',
      label:'👋 Introducing LYNC'
    },
    {
      type:'category',
      label:'Products',
      items:[
        'PRODUCTS/account-abstraction',
        'PRODUCTS/account-abstraction-webgl',
        'PRODUCTS/metamask-wallet',
        'PRODUCTS/metamask-sdk',
        'PRODUCTS/okx-wallet',
        'PRODUCTS/in-game-marketplace',
        'PRODUCTS/nft-fetcher',
        'PRODUCTS/no-code-deployer',
        {
          type:'category',
          label:'EVM Lootbox SDK',
          link:{
            type: 'doc',
            id:'PRODUCTS/evm-lootbox-sdk/evm-lootbox-sdk'
          },
          items:[
            'PRODUCTS/evm-lootbox-sdk/feat/evm-lootbox-sdk-getting-started',
            {
              type:'category',
              label:'Using the SDK',
              link:{
                type: 'doc',
                id:'PRODUCTS/evm-lootbox-sdk/feat/using-sdk/evm-lootbox-sdk-using-sdk'
              },
              items:[
                'PRODUCTS/evm-lootbox-sdk/feat/using-sdk/feat/evm-lootbox-sdk-create-new',
                'PRODUCTS/evm-lootbox-sdk/feat/using-sdk/feat/evm-lootbox-sdk-open',
                'PRODUCTS/evm-lootbox-sdk/feat/using-sdk/feat/evm-lootbox-sdk-claim',
                'PRODUCTS/evm-lootbox-sdk/feat/using-sdk/feat/evm-lootbox-sdk-whitelist',
                'PRODUCTS/evm-lootbox-sdk/feat/using-sdk/feat/evm-lootbox-sdk-admin',
                'PRODUCTS/evm-lootbox-sdk/feat/using-sdk/feat/evm-lootbox-sdk-useful-information',
                'PRODUCTS/evm-lootbox-sdk/feat/using-sdk/feat/evm-lootbox-sdk-multicall',
              ]
            },
            {
              type:'category',
              label:'Example Codes in React & TypeScript',
              link:{
                type: 'doc',
                id:'PRODUCTS/evm-lootbox-sdk/feat/example-codes/evm-lootbox-sdk-example-codes'
              },
              items:[
                'PRODUCTS/evm-lootbox-sdk/feat/example-codes/feat/evm-lootbox-sdk-example-codes-create',
                'PRODUCTS/evm-lootbox-sdk/feat/example-codes/feat/evm-lootbox-sdk-example-codes-open',
                'PRODUCTS/evm-lootbox-sdk/feat/example-codes/feat/evm-lootbox-sdk-example-codes-claim',
              ]
            }
          ]
        },
        {
          type:'category',
          label:'Launch your products on Telegram',
          link:{
            type: 'doc',
            id:'PRODUCTS/telegram/telegram-launch'
          },
          items:[
            'PRODUCTS/telegram/telegram-conf',
            'PRODUCTS/telegram/telegram-deploy',
          ]
        }
      ]
    },
    // {
    //   type: 'doc',
    //   id: 'graphql-example',
    //   label:'GraphQL Example'
    // },
    {
      type: 'category',
      label: 'APTOS',
      // link:{
      //   type: 'doc',
      //   id:'FUEL/fuel'
      // },
      items:[
        {
          type:'category',
          label:'LYNC Paymaster - Supporting Aptos',
          link:{
            type: 'doc',
            id:'APTOS/paymaster/aptos-paymaster'
          },
          items:[
            'APTOS/paymaster/feat/aptos-paymaster-register-on-dashboard',
            'APTOS/paymaster/feat/aptos-paymaster-create-paymaster',
            'APTOS/paymaster/feat/aptos-paymaster-fund-paymaster',
            'APTOS/paymaster/feat/aptos-paymaster-module-and-function-whitelist',
            {
              type: "category",
              label: "How to Integrate Paymaster",
              items: [
                'APTOS/paymaster/feat/integration/aptos-paymaster-integration-unity',
                'APTOS/paymaster/feat/integration/aptos-paymaster-integration-api',
                'APTOS/paymaster/feat/integration/aptos-paymaster-integration-js-ts',
              ],
            },
            
          ]
        },
        'APTOS/unity-sdk/aptos-unity-sdk',
        {
          type:'category',
          label:'Keyless Accounts',
          link:{
            type: 'doc',
            id:'APTOS/keyless-accounts/aptos-keyless-accounts'
          },
          items:[
            'APTOS/keyless-accounts/aptos-keyless-accounts-oidc',
            'APTOS/keyless-accounts/aptos-keyless-accounts-integrate-keyless',

          ]
        },
        {
          type:'category',
          label:'Wallet Creation and Transaction APIs',
          link:{
            type: 'doc',
            id:'APTOS/wallet-apis/aptos-wallet'
          },
          items:[
            'APTOS/wallet-apis/prerequisites/prerequisites',
            {
              type:'category',
              label:'Integration',
              link:{
                type: 'doc',
                id:'APTOS/wallet-apis/integration/integration'
              },
              items:[
                'APTOS/wallet-apis/integration/feat/aptos-overview',
                'APTOS/wallet-apis/integration/feat/aptos-create-wallet',
                'APTOS/wallet-apis/integration/feat/aptos-get-created-wallet',
                'APTOS/wallet-apis/integration/feat/aptos-mint-nft-transactions',
                'APTOS/wallet-apis/integration/feat/aptos-generic-transaction',
                
              ]
            }
          ],
          
        },
        {
          type:'category',
          label:'LYNC Social Login SDK on Aptos',
          link:{
            type: 'doc',
            id:'APTOS/social-login/aptos-social-login'
          },
          items:[
            'APTOS/social-login/feat/aptos-social-login-getting-started',
            'APTOS/social-login/feat/aptos-social-login-using-sdk',
            'APTOS/social-login/feat/aptos-social-login-example-codes',
            'APTOS/social-login/feat/aptos-social-login-types',
            'APTOS/social-login/feat/aptos-social-login-specification',
            

          ]
        },
        {
          type:'category',
          label:'LYNC Aptos Lootbox',
          link:{
            type: 'doc',
            id:'APTOS/lootbox/aptos-lootbox'
          },
          items:[
            'APTOS/lootbox/feat/aptos-lootbox-start',
            'APTOS/lootbox/feat/aptos-lootbox-create',
            'APTOS/lootbox/feat/aptos-lootbox-open',
            'APTOS/lootbox/feat/aptos-lootbox-claim',
            'APTOS/lootbox/feat/aptos-lootbox-conclusion',
          ]
        }
      ]
      
    },
    {
      type: 'category',
      label: 'Movement Labs',
      // link:{
      //   type: 'doc',
      //   id:'FUEL/fuel'
      // },
      items:[
        // {
        //   type: 'category',
        //   label:'📇 Indexer',
        //   link:{
        //     type: 'doc',
        //     id:'MOVEMENT/indexer/movement-indexer'
        //   },
        //   items:[
        //     'MOVEMENT/indexer/movement-indexer-how-to-run',
        //     {
        //       type:'category',
        //       label:'Example Queries',
        //       items:[
        //         'MOVEMENT/indexer/examples/movement-indexer-example-1',
        //         'MOVEMENT/indexer/examples/movement-indexer-example-2',
        //         'MOVEMENT/indexer/examples/movement-indexer-example-3',
        //       ]
        //     }
        //   ]
        // },
        'MOVEMENT/nft-deployer/movement-nft-deployer',
        {
          type:'category',
          label:'LYNC Social Login SDK on Movement',
          link:{
            type: 'doc',
            id:'MOVEMENT/social-login/movement-social-login'
          },
          items:[
            'MOVEMENT/social-login/feat/movement-social-login-getting-started',
            'MOVEMENT/social-login/feat/movement-social-login-using-sdk',
            'MOVEMENT/social-login/feat/movement-social-login-example-codes',
            'MOVEMENT/social-login/feat/movement-social-login-types',
            'MOVEMENT/social-login/feat/movement-social-login-specification',
            

          ]
        },
        'MOVEMENT/unity-sdk/movement-unity-sdk',
        {
          type:'category',
          label:'Wallet Creation and Transaction APIs',
          link:{
            type: 'doc',
            id:'MOVEMENT/wallet-apis/movement-wallet'
          },
          items:[
            'MOVEMENT/wallet-apis/prerequisites/prerequisites',
            {
              type:'category',
              label:'Integration',
              link:{
                type: 'doc',
                id:'MOVEMENT/wallet-apis/integration/integration'
              },
              items:[
                'MOVEMENT/wallet-apis/integration/feat/movement-overview',
                'MOVEMENT/wallet-apis/integration/feat/movement-create-wallet',
                'MOVEMENT/wallet-apis/integration/feat/movement-get-created-wallet',
                'MOVEMENT/wallet-apis/integration/feat/movement-mint-nft-transactions',

              ]
            }
          ],
          
        },
        {
          type:'category',
          label:'LYNC Paymaster - Supporting Movement',
          link:{
            type: 'doc',
            id:'MOVEMENT/paymaster/movement-paymaster'
          },
          items:[
            'MOVEMENT/paymaster/feat/movement-paymaster-register-on-dashboard',
            'MOVEMENT/paymaster/feat/movement-paymaster-create-paymaster',
            'MOVEMENT/paymaster/feat/movement-paymaster-fund-paymaster',
            'MOVEMENT/paymaster/feat/movement-paymaster-module-and-function-whitelist',
            {
              type: "category",
              label: "How to Integrate Paymaster",
              items: [
                'MOVEMENT/paymaster/feat/integration/movement-paymaster-integration-js-ts',
              ],
            },
            
          ]
        },
        
      ]
      
    },
    {
      type: 'category',
      label: 'SUPRA',
      
      items:[
        {
          type:'category',
          label:'LYNC Paymaster - Supporting Supra L1',
          link:{
            type: 'doc',
            id:'SUPRA/paymaster/supra-paymaster'
          },
          items:[
            'SUPRA/paymaster/feat/supra-paymaster-register-on-dashboard',
            'SUPRA/paymaster/feat/supra-paymaster-create-paymaster',
            'SUPRA/paymaster/feat/supra-paymaster-fund-paymaster',
            'SUPRA/paymaster/feat/supra-paymaster-module-and-function-whitelist',
            {
              type: "category",
              label: "How to Integrate Paymaster",
              items: [
                'SUPRA/paymaster/feat/integration/supra-paymaster-integration-js-ts',
              ],
            },
            
          ]
        },
        'SUPRA/unity-sdk/supra-unity-sdk',
        {
          type:'category',
          label:'Wallet Creation and Transaction APIs',
          link:{
            type: 'doc',
            id:'SUPRA/wallet-apis/supra-wallet'
          },
          items:[
            'SUPRA/wallet-apis/prerequisites/prerequisites',
            {
              type:'category',
              label:'Integration',
              link:{
                type: 'doc',
                id:'SUPRA/wallet-apis/integration/integration'
              },
              items:[
                'SUPRA/wallet-apis/integration/feat/supra-overview',
                'SUPRA/wallet-apis/integration/feat/supra-create-wallet',
                'SUPRA/wallet-apis/integration/feat/supra-get-created-wallet',
                'SUPRA/wallet-apis/integration/feat/supra-mint-nft-transactions',
                
              ]
            }
          ],
          
        },
        // {
        //   type:'category',
        //   label:'Wallet Creation and Transaction APIs',
        //   link:{
        //     type: 'doc',
        //     id:'FUEL/wallet-apis/fuel-wallet'
        //   },
        //   items:[
              
        //     'FUEL/wallet-apis/prerequisites/prerequisites',
        //     {
        //       type:'category',
        //       label:'Integration',
        //       link:{
        //         type: 'doc',
        //         id:'FUEL/wallet-apis/integration/integration'
        //       },
        //       items:[
        //         'FUEL/wallet-apis/integration/feat/fuel-overview',
        //         'FUEL/wallet-apis/integration/feat/fuel-create-wallet',
        //         'FUEL/wallet-apis/integration/feat/fuel-get-created-wallet',

        //       ]
        //     }
            
        //   ],
          
        // }
      ]
      
    },
    {
      type: 'category',
      label: 'FUEL',
      // link:{
      //   type: 'doc',
      //   id:'FUEL/fuel'
      // },
      items:[
        'FUEL/unity-sdk/fuel-unity-sdk',
        {
          type:'category',
          label:'LYNC NFT Deployer',
          link:{
            type: 'doc',
            id:'FUEL/deployer/fuel-deployer'
          },
          items:[
            'FUEL/deployer/fuel-deployer-intro',
            'FUEL/deployer/fuel-deployer-start',
            {
              type:'category',
              label:'Deploying Your NFTs',
              link:{
                type: 'doc',
                id:'FUEL/deployer/deploy/fuel-deployer-deploy'
              },
              items:[
                'FUEL/deployer/deploy/fuel-deployer-launch'
              ]
            },
            'FUEL/deployer/fuel-deployer-faqs',
          ]
        },
        {
          type:'category',
          label:'LYNC Fuel Lootbox',
          link:{
            type: 'doc',
            id:'FUEL/lootbox/fuel-lootbox'
          },
          items:[
            'FUEL/lootbox/feat/fuel-lootbox-start',
            'FUEL/lootbox/feat/fuel-lootbox-create',
            'FUEL/lootbox/feat/fuel-lootbox-open',
            'FUEL/lootbox/feat/fuel-lootbox-claim',
            'FUEL/lootbox/feat/fuel-lootbox-conclusion',
          ]
        },
        {
          type:'category',
          label:'Wallet Creation and Transaction APIs',
          link:{
            type: 'doc',
            id:'FUEL/wallet-apis/fuel-wallet'
          },
          items:[
              
            'FUEL/wallet-apis/prerequisites/prerequisites',
            {
              type:'category',
              label:'Integration',
              link:{
                type: 'doc',
                id:'FUEL/wallet-apis/integration/integration'
              },
              items:[
                'FUEL/wallet-apis/integration/feat/fuel-overview',
                'FUEL/wallet-apis/integration/feat/fuel-create-wallet',
                'FUEL/wallet-apis/integration/feat/fuel-get-created-wallet',

              ]
            }
            
          ],
          
        },
        {
          type:'category',
          label:'Fuel Marketplace NPM SDK',
          link:{
            type: 'doc',
            id:'FUEL/marketplace-sdk/fuel-marketplace-sdk'
          },
          items:[
            'FUEL/marketplace-sdk/fuel-marketplace-sdk-start',
            {
              type:"category",
              label:'Using the SDK',
              link:{
                type: 'doc',
                id:'FUEL/marketplace-sdk/using/fuel-marketplace-sdk-using'
              },
              items:[
                'FUEL/marketplace-sdk/using/fuel-marketplace-sdk-using-hooks',
                'FUEL/marketplace-sdk/using/fuel-marketplace-sdk-using-services',
                'FUEL/marketplace-sdk/using/fuel-marketplace-sdk-using-functions',
                'FUEL/marketplace-sdk/using/fuel-marketplace-sdk-using-errors',
                'FUEL/marketplace-sdk/using/fuel-marketplace-sdk-using-interface',
              ]
            },
            'FUEL/marketplace-sdk/fuel-marketplace-sdk-support',
          ]
        }
      ]
      
    },
    
    
    // {
    //   type:'category',
    //   label:'METIS',
    //   items:[
    //     {
    //       type:'category',
    //       label:'Wallet Creation and Transaction APIs',
    //       link:{
    //         type: 'doc',
    //         id:'METIS/wallet-apis/metis-wallet'
    //       },
    //       items:[
    //         'METIS/wallet-apis/prerequisites/prerequisites',
    //         {
    //           type:'category',
    //           label:'Integration',
    //           link:{
    //             type: 'doc',
    //             id:'METIS/wallet-apis/integration/integration'
    //           },
    //           items:[
    //             'METIS/wallet-apis/integration/feat/metis-overview',
    //             'METIS/wallet-apis/integration/feat/metis-create-wallet',
    //             'METIS/wallet-apis/integration/feat/metis-get-created-wallet',
    //             'METIS/wallet-apis/integration/feat/metis-mint-nft-transactions',

    //           ]
    //         }
    //       ],
          
    //     },
    //   ]
    // },
    {
      type:'category',
      label:'NPM PACKAGES',
      link:{
        type: 'doc',
        id:'NPM-PACKAGES/marketplace/packages-marketplace'
      },
      items:[
        'NPM-PACKAGES/marketplace/packages-marketplace-useAllCollectionNFT',
        'NPM-PACKAGES/marketplace/packages-marketplace-useAllBuyNFT',
        'NPM-PACKAGES/marketplace/packages-marketplace-useAllOwnerNFT',
        'NPM-PACKAGES/marketplace/packages-marketplace-useNFTDetails',
        'NPM-PACKAGES/marketplace/packages-marketplace-useAllNFTForRent',
      ]
    }
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  ],
  
};

export default sidebars;
